add action to create PR-specific apps
districtr/districtr-v2 pull request #116
Opened 2024-09-28 18:04 UTC by mariogiampieri

test; will likely need to update snapshot index invocation

## Description

- Testing github actions to create pr-specific apps for testing before merging into main

## Reviewers

- Primary:
- Secondary:

## Checklist

- [ ] Added/Updated related documentation (if applicable).
- [ ] Added/Updated related unit tests (if applicable).

## Screenshots (if applicable):

2024-10-16 13:04 UTC, raphaellaude requested changes
Looks super good. I like how the action skips rebuilding the db + apps if they exist 🤗 . Just a few small comments

2024-10-17 02:50 UTC, mariogiampieri commented on app/fly.toml
> +  min_machines_running = 2
yup yup, was just testing but agreed it's overkill for a pr branch

2024-10-17 02:51 UTC, mariogiampieri commented on app/Dockerfile
> +RUN echo $NEXT_PUBLIC_S3_BUCKET_URL
good call!

2024-10-17 02:52 UTC, mariogiampieri commented on app/fly.toml
> +  auto_stop_machines = true
noted, and fine with having a different approach for prod vs testing later

2024-10-17 02:55 UTC, mariogiampieri commented on .github/workflows/fly-deploy-pr.yml
> +              working-directory: backend
i think that's right- you all did a great job with the backend documentation and people may end up having to futz with specific migrations if they aren't careful per your point. happy to leave for now, maybe worth changing the boilerplate PR text to state clearly what will happen on each PR?

2024-10-18 13:02 UTC, raphaellaude approved these changes
lgtm

2024-10-19 14:44 UTC, mariogiampieri commented
Rebased, added some documentation, and successfully tested shattering on the pr app. I manually removed the app so as to not waste resources but we should be good to go now.

2024-10-21 12:32 UTC, raphaellaude approved these changes
lgtm

2024-10-21 12:44 UTC, raphaellaude commented
@mariogiampieri I need this to test a feature real quick so I'm going to merge. Ty!

2024-10-21 12:44 UTC, merged