[Fixes #213] Fix tpop buf
districtr/districtr-v2 pull request #219
Opened 2024-12-05 11:58 UTC by raphaellaude

## Description

- Fixes #213 

## Reviewers

- Primary: @nofurtherinformation @mariogiampieri 
- Secondary:

## Checklist

- [ ] Added/Updated related documentation (if applicable).
- [x] Added/Updated related unit tests (if applicable).

## Screenshots (if applicable):

2024-12-05 15:48 UTC, nofurtherinformation requested changes
One picky minor thing in the JSX but otherwise LGTM!

2024-12-05 15:48 UTC, nofurtherinformation commented on app/src/app/components/sidebar/charts/HorizontalBarChart.tsx
> +      return <div>Error: {mapMetrics?.error.response.data.detail}</div>;
PP: Remove extra conditional and return and have inline option chaining, like:

```javascript
<div>
  Error: {mapMetrics?.error.response.data.detail || mapMetrics?.error?.message}
</div>
```

2024-12-05 15:48 UTC, nofurtherinformation commented on app/src/app/store/mapStore.ts
> +  response: APIErrorResponse
Nice

2024-12-23 05:11 UTC, raphaellaude commented
@nofurtherinformation this is finally ready for review! Working as expected in the test app :)

2024-12-23 19:39 UTC, nofurtherinformation approved these changes
lgtm! (may need one more mergeroni)

2024-12-24 19:52 UTC, merged