Hovered features should reset after mouse leaves the map
districtr/districtr-v2 pull request #228
Opened 2024-12-29 05:13 UTC by mapmeld

Bug was repeatable: having the cursor leave the map while painting leaves that area shaded until you resume painting, this can be a longer time if you change to the move cursor

<img width="444" alt="Screenshot 2024-12-28 at 11 34 13 PM" src="https://github.com/user-attachments/assets/b9619621-a037-4828-a2cb-f69741d4d65b" />
<img src="https://github.com/user-attachments/assets/ef42a1b9-9e97-41f2-9601-d79a485d3538" width="444"/>

Proposed solution: `useHoverStore` gives us a function to clear the hover features; this requires a short timeout to avoid the map re-selecting these features

2024-12-31 19:47 UTC, nofurtherinformation requested changes
Just a code org suggestion but this approach works!

2024-12-31 19:47 UTC, nofurtherinformation commented on app/src/app/components/Map.tsx
> +      setTimeout(() => setHoverFeatures([]), 250);
H: Timeout approach seems to work here, but this should be in `mapEvents.ts` > `handleMapMouseOut. Unless this needs to rely on the component lifecycle?

2025-01-02 01:19 UTC, mapmeld commented on app/src/app/components/Map.tsx
> +      setTimeout(() => setHoverFeatures([]), 250);
:+1: looks like I can add a timeout to the two places where hover features are reset to the empty array, moved the changes into there

2025-01-02 14:52 UTC, nofurtherinformation commented on app/src/app/components/Map.tsx
> +      setTimeout(() => setHoverFeatures([]), 250);
Thank you!

2025-01-02 14:54 UTC, nofurtherinformation approved these changes
Splendid!

2025-01-02 14:54 UTC, merged